export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: { Row: { id: string; full_name: string; mobile_number: string; address: string | null; created_at: string; updated_at: string }; Insert: { id: string; full_name: string; mobile_number: string; address?: string | null; created_at?: string; updated_at?: string }; Update: { id?: string; full_name?: string; mobile_number?: string; address?: string | null; created_at?: string; updated_at?: string } };
      chefs: { Row: { id: string; user_id: string | null; chef_name: string; brand_name: string; profile_picture_url: string; city: string; created_at: string }; Insert: { id?: string; user_id?: string | null; chef_name: string; brand_name: string; profile_picture_url: string; city: string; created_at?: string }; Update: { id?: string; user_id?: string | null; chef_name?: string; brand_name?: string; profile_picture_url?: string; city?: string; created_at?: string } };
      restaurants: { Row: { id: string; hotel_name: string; city: string; address: string | null; created_at: string }; Insert: { id?: string; hotel_name: string; city: string; address?: string | null; created_at?: string }; Update: { id?: string; hotel_name?: string; city?: string; address?: string | null; created_at?: string } };
      home_made_foods: { Row: { id: string; chef_id: string; food_name: string; description: string; category: 'meals' | 'snacks' | 'desserts'; price: number; image_url: string; calories: number; protein: number; prebooking_hours: number; available: boolean; created_at: string }; Insert: { id?: string; chef_id: string; food_name: string; description: string; category: 'meals' | 'snacks' | 'desserts'; price: number; image_url: string; calories?: number; protein?: number; prebooking_hours?: number; available?: boolean; created_at?: string }; Update: { id?: string; chef_id?: string; food_name?: string; description?: string; category?: 'meals' | 'snacks' | 'desserts'; price?: number; image_url?: string; calories?: number; protein?: number; prebooking_hours?: number; available?: boolean; created_at?: string } };
      restaurant_made_foods: { Row: { id: string; restaurant_id: string; food_name: string; description: string; category: 'meals' | 'snacks' | 'desserts'; price: number; image_url: string; calories: number; protein: number; available: boolean; created_at: string }; Insert: { id?: string; restaurant_id: string; food_name: string; description: string; category: 'meals' | 'snacks' | 'desserts'; price: number; image_url: string; calories?: number; protein?: number; available?: boolean; created_at?: string }; Update: { id?: string; restaurant_id?: string; food_name?: string; description?: string; category?: 'meals' | 'snacks' | 'desserts'; price?: number; image_url?: string; calories?: number; protein?: number; available?: boolean; created_at?: string } };
      cart_items: { Row: { id: string; user_id: string; food_type: 'home_made' | 'restaurant_made'; food_id: string; quantity: number; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; food_type: 'home_made' | 'restaurant_made'; food_id: string; quantity?: number; created_at?: string; updated_at?: string }; Update: { id?: string; user_id?: string; food_type?: 'home_made' | 'restaurant_made'; food_id?: string; quantity?: number; created_at?: string; updated_at?: string } };
      orders: { Row: { id: string; user_id: string; order_number: string; total_amount: number; delivery_address: string; payment_id: string | null; payment_status: string; order_status: string; created_at: string }; Insert: { id?: string; user_id: string; order_number: string; total_amount: number; delivery_address: string; payment_id?: string | null; payment_status?: string; order_status?: string; created_at?: string }; Update: { id?: string; user_id?: string; order_number?: string; total_amount?: number; delivery_address?: string; payment_id?: string | null; payment_status?: string; order_status?: string; created_at?: string } };
      order_items: { Row: { id: string; order_id: string; food_type: string; food_id: string; food_name: string; quantity: number; price: number; created_at: string }; Insert: { id?: string; order_id: string; food_type: string; food_id: string; food_name: string; quantity: number; price: number; created_at?: string }; Update: { id?: string; order_id?: string; food_type?: string; food_id?: string; food_name?: string; quantity?: number; price?: number; created_at?: string } };
    };
  };
}
